# Milestone 1: Consumer Intent
#### Joshua Greenert
#### DSC550-T301 Data Mining
#### 10/8/2022

In [4]:
# What is the best time to advertise to online customers?
import pandas as pd
import matplotlib as plt

df_consumer = pd.read_csv('online_shoppers_intention.csv')
df_consumer.head(5)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [5]:
# Create a function to clean the data within the dataframe.
def prepare_data(df):

IndentationError: expected an indented block (2601568998.py, line 3)